server:
  port: 80

zuul:
  routes:
    add-service-demo:
      path: /add-service/**
      serviceId: add-service-sky
    random-service-demo:
      path: /random-service/**
      serviceId: random-service-sky

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
